1. Create a 5X2 integer array and Prints its attributes?

In [6]:
import numpy as np


In [16]:
lst=[4,5,3,5,6,7,7,6,8,9]
arr=np.array(lst,dtype=np.uint16)
arr=arr.reshape(5,2)
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.itemsize)

[[4 5]
 [3 5]
 [6 7]
 [7 6]
 [8 9]]
(5, 2)
2
2


2. Create an array by adding the following two NumPy arrays.
Next, modify the result array by calculating the square of each
element.

In [26]:
import numpy as np
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])
newarray=arrayOne+arrayTwo
print("addition of two arrays is \n")
print(newarray)

print ("Square Value of newarray : \n", np.square(newarray))

addition of two arrays is 

[[20 39 33]
 [25 25 28]]
Square Value of arr1 : 
 [[ 400 1521 1089]
 [ 625  625  784]]


3.Find the length of each string element in the Numpy array

In [29]:
import numpy as np

array = np.array(['Ram','Shyam','Ghanshyam'])
print(array)
length_checker = np.vectorize(len)
arr_len = length_checker(array)
print(arr_len)

['Ram' 'Shyam' 'Ghanshyam']
[3 5 9]


4. Find Mean ,median and mode of a List of Numpy Array

In [44]:
import numpy as np
from scipy import stats
lst=[4,5,3,5,6,7,7,6,8,9]
x= np.mean(lst)
print("Mean of the array is=",x)
y=np.median(lst)
print("Median of the array is=",y)
Z= stats.mode(lst)
print("Mode of the array is=",Z)

Mean of the array is= 6.0
Median of the array is= 6.0
Mode of the array is= ModeResult(mode=5, count=2)


5.Calculate the Euclidean distance using NumPy

In [54]:
import numpy as np
arrayOne = np.array([5, 6,7])
arrayTwo = np.array([8 ,9,10])
print(arrayOne)
print(arrayTwo)
square = np.square(arrayOne - arrayTwo)
print(square)
sum_square = np.sum(square)
print(sum_square)
distance = np.sqrt(sum_square)
print("Euclidean distance is =",distance)

[5 6 7]
[ 8  9 10]
[9 9 9]
27
Euclidean distance is = 5.196152422706632


6.COVID-19 Data Visualization using matplotlib in Python

In [59]:
import matplotlib.pyplot as plt 
import csv 
  
x = [] 
y = [] 
  
with open('case_time_series.csv','r') as csvfile: 
    lines = csv.reader(csvfile) 
    for row in lines: 
        x.append(row[0]) 
        y.append(int(row[1])) 
  
plt.plot(x, y, color = 'g', linestyle = 'dashed', 
         marker = 'o',label = "Covid patient") 
  
plt.xticks(rotation = 25) 
plt.xlabel('Dates') 
plt.ylabel('TDaily Confirmed') 
plt.title('Covid patient', fontsize = 20) 
plt.grid() 
plt.legend() 
plt.show() 

ValueError: invalid literal for int() with base 10: 'Daily Confirmed'